short_names = {
    "A Link to the Past": "ALttP",
    "Castlevania - Circle of the Moon": "CV: CotM",
    "Diddy Kong Racing": "DKR",
    "Donkey Kong Country": "DKC",
    "Donkey Kong Country 2": "DKC2",
    "Donkey Kong Country 3": "DKC3",
    "Final Fantasy Mystic Quest": "FFMQ",
    "Kingdom Hearts": "KH1",
    "Kingdom Hearts 2": "KH2",
    "Kirby 64 - The Crystal Shards": "K64",
    "Kirby Super Star": "KSS",
    "Kirby's Dream Land 3": "KDL3",
    "Mario & Luigi Superstar Saga": "MLSS",
    "Mario Kart Double Dash": "MKDD",
    "Paper Mario": "PM64",
    "Paper Mario: The Thousand-Year Door": "TTYD",
    "Pokemon Crystal": "PKMN: Crystal",
    "Pokemon Emerald": "PKMN: Emerald",
    "Pokemon FireRed and LeafGreen": "PKMN: FRLG",
    "Pokemon Red and Blue": "PKMN: RB",
    "Skyward Sword": "TLoZ: SS",
    "Sonic Adventure 2 Battle": "SA2B",
    "Super Mario World": "SMW",
    "Super Mario Sunshine": "SMS",
    "Symphony of the Night": "CV: SotN",
    "The Binding of Isaac Repentance": "TBoIR",
    "The Legend of Zelda": "TLoZ",
    "Zelda II: The Adventure of Link": "Zelda II",
    "Twilight Princess": "TLoZ: TP",
    "The Wind Waker": "TLoZ: WW",
    "Links Awakening DX": "LADX",
    "The Legend of Zelda - Oracle of Seasons": "TLoZ: OoS",
    "The Legend of Zelda - Oracle of Ages": "TLoZ: OoA",
    "The Minish Cap": "TLoZ: TMC",
    "A Link Between Worlds": "TLoZ: ALBW",
    "Majora's Mask Recompiled": "TLoZ: MM",
    "Ocarina of Time": "TLoZ: OoT",
    "Metroid Zero Mission": "Metroid ZM",
    "Castlevania - Harmony of Dissonance": "CV: HoD",
    "Castlevania: Dawn of Sorrow": "CV: DoS",
    "Final Fantasy IV Free Enterprise": "FF4",
    "Final Fantasy 6 Worlds Collide": "FF6",
    "Golden Sun The Lost Age": "Golden Sun",
    "Super Mario Land 2": "SML2",
    "Sonic Adventure DX": "SADX",
    "The Simpsons Hit And Run": "SHAR",
    "Momodora Moonlit Farewell": "Momodora 5",
    "Yoku's Island Express": "Yoku's Island",
    "Plants vs. Zombies: Replanted": "PvZ: Replanted",
}

aliases = {
    "Celeste (Open World)": "Celeste",
    "Ship of Harkinian": "Ocarina of Time",
    "SMW: Spicy Mycena Waffles": "Super Mario World",
    "yrtnuoC gnoK yeknoD": "Donkey Kong Country",
    "GZDoom (Doom)": "Doom 1993",
    "GZDoom (Doom 2)": "Doom 1993",
    "GZDoom (Legacy of Rust)": "Doom 1993",
    "GZDoom (Master Levels for Doom II)": "Doom 1993",
    "GZDoom (Plutonia)": "Doom 1993",
    "GZDoom (TNT)": "Doom 1993",
    "GZDoom (Arrival)": "Doom 1993",
    "GZDoom (Base Ganymede)": "Doom 1993",
    "GZDoom (BTSX Episode 1)": "Doom 1993",
    "GZDoom (Deathless)": "Doom 1993",
    "GZDoom (Going Down Turbo)": "Doom 1993",
    "GZDoom (Scientist)": "Doom 1993",
    "GZDoom (1000 Lines)": "Doom 1993",
    "GZDoom (1000 Lines II)": "Doom 1993",
    "GZDoom (Amalgoom)": "Doom 1993",
    "GZDoom (Demonfear): "Doom 1993",
    "GZDoom (MAYhem 2048)": "Doom 1993",
    "GZDoom (Scythe)": "Doom 1993",
    "GZDoom (Scythe 2)": "Doom 1993",
    "GZDoom (Zone 300)": "Doom 1993",
}
